### ISSUE TITLE
Play with for non-stream filetypes (like .mp3 .webm .opus audio files)

### ISSUE THREAD

**Issue by mYnDstrEAm** [grmat/play-with#13]
It would be great if this addon would also allow downloading and playing other filetypes than .m3u streams, especially audio-files.

Depending on the file it would then either wait until the download with youtube-dl has finished and open the file afterwards or play the file (maybe after a short waiting-time depending on the detected download-speed, file-duration & file-size) as it gets downloaded (.part files can also be played with mpv).

The (default) download-location for the files should be configurable with the addon's settings.

It would be good if one could select either "Open with: MPV (audio)" or "MPV (video)".

The youtube-dl command for the audio download should look something like this: `youtube-dl --extract-audio --audio-format best -i -o '/default-download-location/Music/%(title)s.%(ext)s'` and if the source file/website supports and/or it was configured in the settings with additional parameters `--embed-thumbnail --add-metadata`.

**Comment by grmat** [comment]
Hi,

> It would be great if this addon would also allow downloading and playing other filetypes than .m3u streams, especially audio-files.

You have a misconception on what this extension does. It doesn't *support* "M3U streams", it *generates* a M3U playlist file in order to open this file in mpv. If the site or link you're handing to play-with points to an audio file, e.g. https://www.w3schools.com/html/horse.ogg it'll result in a playlist with this exact URL inside. mpv will read it and attempt to play the media from the URL. Whether you can stream this data or you'll have to fully download it first depends on how it is served. You can verify this by right-clicking this exact link, then select `play-with`.


> The (default) download-location for the files should be configurable with the addon's settings.

No, it should not. Nothing of this is handled within the scope of this extension but in your browser's settings.


play-with doesn't do what you think it does. You'll be probably better off looking for another extension with a native component. Please read the README.
